#!/usr/bin/env python3 -i
from moe import *

##
### Welcome Message
##
print("Welcome to the MOO Tool")
print("We've exposed the MOO function for you to use\n")

print("Arguments:")
print("unif_algo: The unification algorithm to use")
print("chaining: The function defining how blocks are chained together")
print("schedule: (str) 'every' or 'end'")
print("length_bound: (int) the bound on the length of interactions between advesary and oracle")
print("[optional] knows_iv: (bool) whether or not the advesary knows the initialization vector\n")

print("Ex: MOE(unif_algo = unif, chaining = cipher_block_chaining, schedule = 'every', length_bound = 10, session_bound = 1, knows_iv = True)\n")

print("For help, type help(argument_name) where argument_name is a string")
print("Ex: help('unif_algo')")


##
### Help Function
##
def help(argument):
    if argument == 'unif_algo':
        print("Available unification algorithms:")
        print("  'p_syntactic' for P Syntactic Unification")
        print("  'p_unif' for P (f-rooted) XOR Unification")
        print("  'XOR_rooted_security for P (xor-rooted) XOR Unification")
        print("Currently planned but not implemeneted unification algorithms:")
        print("  'p_ac' for P-AC Unification")
    elif argument == "chaining":
        print("Note that no quotes are needed for chaining functions.")
        print("Available Chaining Functions:")
        print("  cipher_block_chaining : Cipher Block Chaining")
        print("  propogating_cbc  : Propogating Cipher Block Chaining")
        print("  hash_cbc : Hash Cipher Block Chaining")
        print("  cipher_Feedback : Cipher Feedback")
        print("  output_feedback : Output Feedback")
        print("Currently planned but not implemented chaining functions:")
        print("  counter_mode : Counter Mode")
        print("  accumulated_block_cipher : Accumulated Block Cipher")
        print("  double_hash_cbc : Double Hash Cipher Block Chaining")
    elif argument == "schedule":
        print("Available schedules:")
        print("  'every' the oracle will send a frame everytime the adversary sends a message")
        print("  'end' the oracle will only send a frame when the advesary marks the end of an interaction")
    elif argument == "length_bound":
        print("An integer argument bounding the length of interactions between the adversary and the oracle")
    elif argument == "knows_iv":
        print("A boolean (True/False) indicating whether or not the advesary knows the initialization vector")
    else:
        print("Argument '%s' is not an argument of MOE" % argument)
        print("Arguments of MOE: unif_algo, chaining, schedule, length_bound, session_bound")
